#!/usr/bin/env python

# This is intended as a replacement for "python -c", but with some math library stuff
# included

import sys
from math import *
print sys.argv[1:]
print " ".join(sys.argv[1:])
print eval(" ".join(sys.argv[1:]))

