######################################################################
# This file was *autogenerated* from the file P100.sage.
######################################################################
#!/usr/bin/env sage

def disc(n): return Integer(2)*n*(n-Integer(1))+Integer(1)
def isint(n): return int(n) == n
def issqint(n): return isint(sqrt(n))

iroots = [Integer(1),Integer(4),Integer(21),Integer(120),Integer(697),Integer(4060),Integer(23661),Integer(137904),Integer(803761),Integer(4684660),Integer(27304197),
          Integer(159140520), Integer(927538921),Integer(5406093004),Integer(31509019101)]

def next_start(): return int(n(iroots[-Integer(1)]*iroots[-Integer(1)]/iroots[-Integer(2)]))

def next_root(istart):
    for i in range(Integer(1000000)):
        print i
        ii = istart + i
        if issqint(disc(ii)):
            print ii
            break
    return
