// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... Find the sum of all
// the even-valued terms in the sequence which do not exceed one
// million.

#include <iostream>
using namespace std;
main(){
  int maxn=1000000;
  int im1 = 2, im2 = 1, sum = 2, im = 0;
  for (;;){
    im = im1+im2;
    if (im >= maxn) break;
    if (im % 2 == 0) sum += im;
    im2 = im1;
    im1 = im;
  }
  cout << sum << endl;
}
