#!/usr/bin/env python
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed one million.
"""

from itertools import takewhile,ifilter

def fib_gen():
    yield 0
    yield 1
    n1,n2 = 0,1
    while 1:
        n1,n2 = n2,n1+n2
        yield n2
    return

n = 1000000

it = ifilter(lambda x: x%2 ==0,takewhile(lambda x: x< n,fib_gen()))

print sum(list(it))
