"""
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The
first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
difference, 70 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum
and difference is pentagonal and D = |Pk Pj| is minimised; what is the
value of D?
"""
import psyco; psyco.full()
from sets import Set
nmax = 10000
pents = [i*(3*i-1)/2 for i in range(1,nmax)]
pentset = Set(pents)

for j in range(nmax-1):
    pj = pents[j]
    for k in range(j):
        pk = pents[k]
        s,d = pj+pk,abs(pj-pk)
        if s in pentset and d in pentset:
            print pj,pk,d

