"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from sets import Set

nterms = 100000
tris = Set([n*(n+1)/2 for n in range(nterms)])
pents = Set([n*(3*n-1)/2 for n in range(nterms)])
hexs = Set([n*(2*n-1) for n in range(nterms)])

print tris & pents & hexs


