######################################################################
# This file was *autogenerated* from the file P94-sage.sage.
######################################################################

def area(a,b): return b*sqrt(Integer(4)*a*a-b*b)/Integer(4)

def brute(plimit=Integer(1000)):
    slimit = plimit/Integer(3)+Integer(1)
    sump = Integer(0)
    for a in xrange(Integer(2),slimit):
        for b in [a-Integer(1),a+Integer(1)]:
            if area(a,b).is_integral():
                p = Integer(2)*a+b
                if p > plimit: continue
                sump += p
    print "sump for p < %d = %d" % (plimit,sump)
    return

