######################################################################
# This file was *autogenerated* from the file P95.sage.
######################################################################
#!/usr/bin/env sage

def sum_div(n):
    if n == Integer(1): return Integer(1)
    return sum(n.divisors())-n
def is_perfect(n): return sum_div(n) == n

def gen_cycle(n,limit=Integer(1000000)):
    cycle = []
    while Integer(1):
        if n > limit: break
        if n in cycle: break
        cycle.append(n)
        n = sum_div(n)
    return cycle

def cycle_list(nmax):
    for i in range(Integer(2),nmax):
        cycle = gen_cycle(i)
        if cycle[-Integer(1)] == Integer(1): continue
        print i,cycle
