# This file was *autogenerated* from the file P96-sage.sage.
from sage.all_cmdline import *
#!/usr/bin/env python
"""\
"""

def parse_test():
    data = []
    for line in puzzle1.splitlines():
        data.extend(map(int,list(line)))
    return data

def parse(fname):
    puzzles = []
    f = open(fname)
    while True:
        puzzle = []
        puzzles.append(puzzle)
        title = f.readline()
        if not title: break
        for i in range(Integer(9)):
            line = f.readline()
            line = line.strip()
            puzzle.extend(map(int,list(line)))
    return puzzles

def main():
    puzzles = parse('sudoku.txt')
    sumkey = Integer(0)
    for i in range(Integer(50)):
        puz = sudoku(Matrix(ZZ,Integer(9),puzzles[i]))
        key =  Integer(100)*puz[Integer(0),Integer(0)]+Integer(10)*puz[Integer(0),Integer(1)]+puz[Integer(0),Integer(2)]
        sumkey += key
        print i,key,sumkey
    print sumkey

if __name__ == '__main__': main()
